"""Staging config: moderate thresholds for testing."""

DRY_RUN = True
MAX_BET_USD = 1.00
MIN_THRESHOLD = 0.65
MAX_THRESHOLD = 0.95
PREFERRED_SIDE = "yes"
VIG_TOLERANCE_TIGHT = (0.98, 1.02)
VIG_TOLERANCE_LOOSE = (0.95, 1.05)
MIN_VOLUME = 2000
SCAN_INTERVAL = 30

# Safety limits
DAILY_LOSS_LIMIT_USD = 100.0
MAX_DAILY_TRADES = 50
MAX_POSITION_USD = 50.0
MAX_CONCURRENT_POSITIONS = 10
WALLET_MIN_BALANCE_USD = 5.0
