"""Development config: loose thresholds for testing."""

DRY_RUN = True
MAX_BET_USD = 0.50
MIN_THRESHOLD = 0.30
MAX_THRESHOLD = 0.90
PREFERRED_SIDE = "yes"
VIG_TOLERANCE_TIGHT = (0.98, 1.02)
VIG_TOLERANCE_LOOSE = (0.90, 1.10)
MIN_VOLUME = 500
SCAN_INTERVAL = 10

# Safety limits
DAILY_LOSS_LIMIT_USD = 200.0
MAX_DAILY_TRADES = 100
MAX_POSITION_USD = 25.0
MAX_CONCURRENT_POSITIONS = 20
WALLET_MIN_BALANCE_USD = 1.0
